config.populstat.countries = {
  afghani: 'Afghanistan',
  bahrain: 'Bahrain',
  banglad: 'Bangladesh',
  bhutan: 'Bhutan',
  brunei: 'Brunei',
  cambodi: 'Cambodia',
  china: 'China',
  cyprus: 'Cyprus',
  easttim: 'East Timor', // Also known as Timor-Leste
  hongkon: 'Hong Kong',
  india: 'India',
  indones: 'Indonesia',
  iran: 'Iran',
  iraq: 'Iraq',
  israel: 'Israel',
  japan: 'Japan',
  jordan: 'Jordan',
  kazakhs: 'Kazakhstan',
  kuwait: 'Kuwait',
  kyrgyzs: 'Kyrgyzstan',
  laos: 'Laos',
  lebanon: 'Lebanon',
  malaysi: 'Malaysia',
  maldive: 'Maldives',
  mongoli: 'Mongolia',
  myanmar: 'Myanmar',
  nepal: 'Nepal',
  nkorea: 'North Korea',
  oman: 'Oman',
  pakista: 'Pakistan',
  palesti: 'Palestine',
  philipp: 'Philippines',
  qatar: 'Qatar',
  saudiar: 'Saudi Arabia',
  singapo: 'Singapore',
  skorea: 'South Korea',
  srilank: 'Sri Lanka',
  syria: 'Syria',
  taiwan: 'Taiwan',
  tajikis: 'Tajikistan',
  thailan: 'Thailand',
  turkey: 'Turkey',
  turkmen: 'Turkmenistan',
  unarabe: 'United Arab Emirates',
  uzbekis: 'Uzbekistan',
  vietnam: 'Vietnam',
  yemen: 'Yemen',
  albania: 'Albania',
  andorra: 'Andorra',
  armenia: 'Armenia',
  austria: 'Austria',
  azerbai: 'Azerbaijan',
  belarus: 'Belarus',
  belgium: 'Belgium',
  bosniah: 'Bosnia and Herzegovina',
  bulgari: 'Bulgaria',
  croatia: 'Croatia',
  czechrp: 'Czech Republic',
  denmark: 'Denmark',
  estonia: 'Estonia',
  faeroei: 'Faroe Islands',
  finland: 'Finland',
  france: 'France',
  georgia: 'Georgia', // Country, not US State
  germany: 'Germany',
  greece: 'Greece',
  hungary: 'Hungary',
  iceland: 'Iceland',
  ireland: 'Ireland',
  italy: 'Italy',
  latvia: 'Latvia',
  lithuan: 'Lithuania',
  luxembg: 'Luxembourg',
  macedon: 'North Macedonia',
  malta: 'Malta',
  moldova: 'Moldova',
  monaco: 'Monaco',
  monteng: 'Montenegro',
  netherl: 'Netherlands',
  norway: 'Norway',
  poland: 'Poland',
  portuga: 'Portugal',
  romania: 'Romania',
  russia: 'Russia',
  smarino: 'San Marino',
  slovaki: 'Slovakia',
  sloveni: 'Slovenia',
  spain: 'Spain',
  svalbar: 'Svalbard', // Part of Svalbard and Jan Mayen
  sweden: 'Sweden',
  switzer: 'Switzerland',
  ukraine: 'Ukraine',
  unkingd: 'United Kingdom',
  yugoslf: 'Serbia', // Geographic area reference
  amsamoa: 'American Samoa',
  austral: 'Australia',
  cookisl: 'Cook Islands',
  fiji: 'Fiji',
  frpolyn: 'French Polynesia',
  guam: 'Guam',
  kiribat: 'Kiribati',
  marshal: 'Marshall Islands',
  microne: 'Micronesia', // Federated States of Micronesia
  nauru: 'Nauru',
  newcale: 'New Caledonia',
  newzeal: 'New Zealand',
  niue: 'Niue',
  norfolk: 'Norfolk Island',
  nmarian: 'Northern Mariana Islands',
  palau: 'Palau',
  papuang: 'Papua New Guinea',
  wsamoa: 'Samoa', // Formerly Western Samoa
  solomon: 'Solomon Islands',
  tokelau: 'Tokelau',
  tonga: 'Tonga',
  tuvalu: 'Tuvalu',
  vanuatu: 'Vanuatu',
  wallisf: 'Wallis and Futuna',
  'usas-al': 'Alabama',
  'usas-ak': 'Alaska',
  'usas-az': 'Arizona',
  'usas-ar': 'Arkansas',
  'usas-ca': 'California',
  'usas-co': 'Colorado',
  'usas-ct': 'Connecticut',
  'usas-de': 'Delaware',
  'usas-fl': 'Florida',
  'usas-ga': 'Georgia', // US State, distinct from country
  'usas-hi': 'Hawaii',
  'usas-id': 'Idaho',
  'usas-il': 'Illinois',
  'usas-in': 'Indiana',
  'usas-ia': 'Iowa',
  'usas-ks': 'Kansas',
  'usas-ky': 'Kentucky',
  'usas-la': 'Louisiana',
  'usas-me': 'Maine',
  'usas-md': 'Maryland',
  'usas-ma': 'Massachusetts',
  'usas-mi': 'Michigan',
  'usas-mn': 'Minnesota',
  'usas-ms': 'Mississippi',
  'usas-mo': 'Missouri',
  'usas-mt': 'Montana',
  'usas-ne': 'Nebraska',
  'usas-nv': 'Nevada',
  'usas-nh': 'New Hampshire',
  'usas-nj': 'New Jersey',
  'usas-nm': 'New Mexico',
  'usas-ny': 'New York',
  'usas-nc': 'North Carolina',
  'usas-nd': 'North Dakota',
  'usas-oh': 'Ohio',
  'usas-ok': 'Oklahoma',
  'usas-or': 'Oregon',
  'usas-pa': 'Pennsylvania',
  'usas-ri': 'Rhode Island',
  'usas-sc': 'South Carolina',
  'usas-sd': 'South Dakota',
  'usas-tn': 'Tennessee',
  'usas-tx': 'Texas',
  'usas-ut': 'Utah',
  'usas-vt': 'Vermont',
  'usas-va': 'Virginia',
  'usas-wa': 'Washington',
  'usas-wv': 'West Virginia',
  'usas-wi': 'Wisconsin',
  'usas-wy': 'Wyoming',
  usa: 'United States', // Could be 'United States of America'
  anguill: 'Anguilla',
  antigub: 'Antigua and Barbuda',
  argenti: 'Argentina',
  aruba: 'Aruba',
  bahamas: 'The Bahamas',
  barbado: 'Barbados',
  belize: 'Belize',
  bermuda: 'Bermuda',
  bolivia: 'Bolivia',
  brazil: 'Brazil',
  brvirgi: 'British Virgin Islands',
  canada: 'Canada',
  caymani: 'Cayman Islands',
  chile: 'Chile',
  colombi: 'Colombia',
  costari: 'Costa Rica',
  cuba: 'Cuba',
  dominic: 'Dominica',
  domirep: 'Dominican Republic',
  ecuador: 'Ecuador',
  elsalva: 'El Salvador',
  falklis: 'Falkland Islands',
  frguian: 'French Guiana',
  greenld: 'Greenland',
  grenada: 'Grenada',
  guadelp: 'Guadeloupe',
  guatema: 'Guatemala',
  guyana: 'Guyana',
  haiti: 'Haiti',
  hondura: 'Honduras',
  jamaica: 'Jamaica',
  martini: 'Martinique',
  mexico: 'Mexico',
  montser: 'Montserrat',
  nethant: 'Netherlands Antilles', // Dissolved, but represents the former entity
  nicarag: 'Nicaragua',
  panama: 'Panama',
  paragua: 'Paraguay',
  peru: 'Peru',
  puertri: 'Puerto Rico',
  stkittn: 'Saint Kitts and Nevis',
  stlucia: 'Saint Lucia',
  stvinct: 'Saint Vincent and the Grenadines',
  sgeorgs: 'South Georgia and the South Sandwich Islands',
  surinam: 'Suriname',
  trinidt: 'Trinidad and Tobago',
  turkcai: 'Turks and Caicos Islands',
  uruguay: 'Uruguay',
  venezue: 'Venezuela',
  virgisl: 'US Virgin Islands',
  algeria: 'Algeria',
  angola: 'Angola',
  benin: 'Benin',
  botswan: 'Botswana',
  burkinf: 'Burkina Faso',
  burundi: 'Burundi',
  cameroo: 'Cameroon',
  capever: 'Cape Verde',
  centraf: 'Central African Republic',
  chad: 'Chad',
  comores: 'Comoros',
  congobr: 'Republic of the Congo', // Congo-Brazzaville
  congoki: 'Democratic Republic of the Congo', // Congo-Kinshasa
  ivoryco: 'Ivory Coast', // Also known as Côte d'Ivoire
  djibout: 'Djibouti',
  egypt: 'Egypt',
  equagui: 'Equatorial Guinea',
  eritrea: 'Eritrea',
  ethiopi: 'Ethiopia',
  gabon: 'Gabon',
  gambia: 'The Gambia',
  ghana: 'Ghana',
  guinea: 'Guinea', // Guinea-Conakry
  guinbis: 'Guinea-Bissau',
  kenya: 'Kenya',
  lesotho: 'Lesotho',
  liberia: 'Liberia',
  libya: 'Libya',
  malawi: 'Malawi',
  malegas: 'Madagascar',
  mali: 'Mali',
  maurita: 'Mauritania',
  mauriti: 'Mauritius',
  mayotte: 'Mayotte',
  morocco: 'Morocco',
  mozambi: 'Mozambique',
  namibia: 'Namibia',
  niger: 'Niger',
  nigeria: 'Nigeria',
  reunion: 'Réunion',
  rwanda: 'Rwanda',
  sthelen: 'Saint Helena', //Part of Saint Helena, Ascension and Tristan da Cunha
  stomepr: 'Sao Tome and Principe',
  senegal: 'Senegal',
  seychel: 'Seychelles',
  sierleo: 'Sierra Leone',
  somalia: 'Somalia',
  safrica: 'South Africa',
  sudan: 'Sudan',
  swazila: 'Eswatini', //Formerly Swaziland
  tanzani: 'Tanzania',
  togo: 'Togo',
  tunisia: 'Tunisia',
  uganda: 'Uganda',
  zambia: 'Zambia',
  zimbabw: 'Zimbabwe'
};