config.chandler_modelski.errors = {
  whitelisted_cities: [
    "Adana-Turkey",
    "Alexandria-Egypt",
    "Amarapura-Myanmar", 
    "Augsburg-Germany",
    "Basra-Iraq", 
    "Bussa-Nigeria",
    "Beijing-China",
    "Birmingham-United States of America",
    "Changchun-China",
    "Changzhou-China",
    "Chongqing-China",
    "Cincinnati-United States of America",
    "Cochin-India",
    "Curitiba-Brazil",
    "Datong-China",
    "Delhi-India",
    "Esfahan-Iran",
    "Genova-Italy",
    "Hefei-China",
    "Houston-United States of America",
    "Inwa-Myanmar",
    "Izmail-Ukraine",
    "Kashi-China",
    "Leshan-China",
    "Louisville-United States of America",
    "Luanda-Angola",
    "Luoyang-China",
    "Madrid-Spain",
    "Malaga-Spain",
    "Meerut-India",
    "Melbourne-Australia",
    "Mumbai-India",
    "Nanning-China",
    "New Orleans-United States of America",
    "Oran-Algeria",
    "Osaka-Japan",
    "Padang-Indonesia",
    "Pekalongan-Indonesia",
    "Pittsburgh-United States of America",
    "Potosi-Bolivia",
    "Poznan-Poland",
    "Qiqihar-China",
    "Samarkand-Uzbekistan",
    "Skopje-Macedonia",
    "Sydney-Australia",
    "Taian-China",
    "Taiyuan-China",
    "Tarsus-Turkey",
    "Tehran-Iran",
    "Tokyo-Japan",
    "Tripoli-Libya",
    "Urumqi-China",
    "Vishakhapatnam-India",
    "Wuzhou-China",
    "Xingtai-China",
    "Srirangapatna-India",
    "St. Louis-United States of America",
    "Visakhapatnam-India"
  ]
};